name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . 
          file: ./Dockerfile
          push: true
          tags: |
            "${{ secrets.DOCKERHUB_USERNAME }}/hello-world-site:latest"
            "${{ secrets.DOCKERHUB_USERNAME }}/hello-world-site:${{ github.sha }}"

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-site:latest
          format: 'table'
          exit-code: '0'
