name: Build & Push Docker Image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      # Забираем код из репозитория
      - name: Checkout code
        uses: actions/checkout@v4

      # Настраиваем Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      # Кэш pip для ускорения установки зависимостей    
      - name: Cache pip dependencies
        uses: action/checkout@v4
        with:
           path: ~/.cache/pip
           key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
           restore-keys: |
             pip-${{ runner.os }}-

      # Устанавливаем зависимости (Flask и пр.)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: . 
          file: ./Dockerfile
          push: true
          tags: |
            "${{ secrets.DOCKERHUB_USERNAME }}/hello-world-site:latest"
            "${{ secrets.DOCKERHUB_USERNAME }}/hello-world-site:${{ github.sha }}"

      - name: Scan Docker image with Trivy
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/hello-world-site:latest
          format: 'table'
          exit-code: '0'
